### PR TITLE
V2.0.0

### PR DESCRIPTION
**Pull request by Yu-jinKim**
## Changes
- Remove vcf2xls and vcf_annotator
- Added eggd_vep v1.0.0 and generate_workbook v2.0.1
- Updated generate_bed from v1.1.5 to v1.2.0
- Updated athena from v1.2.2 to v1.4.0

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_reports_workflow/18)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_reports_workflow/18)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`dxworkflow.json` line 30 at r1](https://reviewable.io/reviews/eastgenomics/eggd_dias_reports_workflow/18#-N2X4Kg29FuGR5Ecj80E:-N2X4Kg37FIQ8gcJ0fyH:b-t9aua0) ([raw file](https://github.com/eastgenomics/eggd_dias_reports_workflow/blob/8a3a06b39d9ac91fd48aff3cd45325e8226d968c/dxworkflow.json#L30)):*
> ```JSON
>         "exclude_columns": "BaseQRankSum ClippingRankSum DB ExcessHet FS MLEAC MLEAF MQ MQRankSum QD ReadPosRankSum SOR PL QUAL ID FILTER  CSQ_ClinVar_CLNSIGCONF  CSQ_Allele CSQ_HGNC_ID DP AC AF AN CSQ_SpliceAI_pred_DP_AL CSQ_SpliceAI_pred_DP_AG CSQ_SpliceAI_pred_DP_DG CSQ_SpliceAI_pred_DP_DL",
>         "acmg": true,
>         "rename_columns": "CSQ_Feature=Transcript DP_FMT=DP CSQ_Mastermind_MMID3=MasterMind",
> ```

@mattgarner did we decide on renaming?
___
*[`dxworkflow.json` line 36 at r1](https://reviewable.io/reviews/eastgenomics/eggd_dias_reports_workflow/18#-N2X4uMX4bzP0IZjTyqY:-N2X4uMX4bzP0IZjTyqZ:b-qt4bb8) ([raw file](https://github.com/eastgenomics/eggd_dias_reports_workflow/blob/8a3a06b39d9ac91fd48aff3cd45325e8226d968c/dxworkflow.json#L36)):*
> ```JSON
>         "filter": "bcftools filter -e '(CSQ_Consequence==\"synonymous_variant\" | CSQ_Consequence==\"intron_variant\" | CSQ_Consequence==\"upstream_gene_variant\" | CSQ_Consequence==\"downstream_gene_variant\" | CSQ_Consequence==\"intergenic_variant\" | CSQ_Consequence==\"5_prime_UTR_variant\" | CSQ_Consequence==\"3_prime_UTR_variant\" | CSQ_gnomADe_AF>0.02 | CSQ_gnomADg_AF>0.02 | CSQ_TWE_AF>0.05) & CSQ_HGMD_CLASS!~ \"DM\" & CSQ_ClinVar_CLNSIG!~ \"pathogenic\\/i\" & CSQ_ClinVar_CLNSIGCONF!~ \"pathogenic\\/i\"'",
>         "human_filter": "excluded gnomAD exomes / genomes > 1%, TWE > 5%, synonymous / intronic / intergenic / upstream / downstream / UTRs EXCEPT pathogenic status in ClinVar OR DM in HGMD Class",
>         "reorder_columns": "CHROM POS REF ALT GT GQ DP_FMT AD CSQ_SYMBOL CSQ_EXON CSQ_INTRON CSQ_HGVSc CSQ_HGVSp CSQ_Consequence CSQ_IMPACT CSQ_VARIANT_CLASS CSQ_gnomADe_AF CSQ_gnomADe_Hom CSQ_gnomADe_AC CSQ_gnomADe_AN CSQ_gnomADg_AF CSQ_gnomADg_Hom CSQ_gnomADg_AC CSQ_gnomADg_AN CSQ_TWE_AF CSQ_TWE_AC_Hom CSQ_TWE_AC_Het CSQ_TWE_AC_Hemi CSQ_TWE_AN CSQ_HGMD CSQ_HGMD_CLASS CSQ_HGMD_RANKSCORE CSQ_HGMD_PHEN CSQ_Existing_variation CSQ_ClinVar CSQ_ClinVar_CLNDN CSQ_ClinVar_CLNSIG CSQ_Mastermind_MMID3 CSQ_CADD_PHRED CSQ_REVEL CSQ_SpliceAI_pred_DS_AG CSQ_SpliceAI_pred_DS_AL CSQ_SpliceAI_pred_DS_DG CSQ_SpliceAI_pred_DS_DL CSQ_HGNC_ID CSQ_HGVS_OFFSET CSQ_STRAND CSQ_Feature",
> ```

these can be removed as they are no longer in the vcfs: `'CSQ_TWE_AC_Hemi', 'CSQ_HGNC_ID', 'CSQ_gnomADg_Hom'`

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_reports_workflow/18)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`dxworkflow.json` line 36 at r1](https://reviewable.io/reviews/eastgenomics/eggd_dias_reports_workflow/18#-N2X4uMX4bzP0IZjTyqY:-N2kJ8up0j42BUU1hCQR:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_dias_reports_workflow/blob/8a3a06b39d9ac91fd48aff3cd45325e8226d968c/dxworkflow.json#L36)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

these can be removed as they are no longer in the vcfs: `'CSQ_TWE_AC_Hemi', 'CSQ_HGNC_ID', 'CSQ_gnomADg_Hom'`
</blockquote></details>

Done.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_reports_workflow/18)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @Yu-jinKim)

___
*[`dxworkflow.json` line 30 at r1](https://reviewable.io/reviews/eastgenomics/eggd_dias_reports_workflow/18#-N2X4Kg29FuGR5Ecj80E:-N2pG9pv00XHVuaIosKc:bhq5zbv) ([raw file](https://github.com/eastgenomics/eggd_dias_reports_workflow/blob/8a3a06b39d9ac91fd48aff3cd45325e8226d968c/dxworkflow.json#L30)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

@mattgarner did we decide on renaming?
</blockquote></details>

@yu-jinkim mastermind can be removed from here

**Review by Yu-jinKim — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_reports_workflow/18)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @mattgarner)

___
*[`dxworkflow.json` line 30 at r1](https://reviewable.io/reviews/eastgenomics/eggd_dias_reports_workflow/18#-N2X4Kg29FuGR5Ecj80E:-N2pHwAYEY1Yjpb99T0J:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_dias_reports_workflow/blob/8a3a06b39d9ac91fd48aff3cd45325e8226d968c/dxworkflow.json#L30)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

@yu-jinkim mastermind can be removed from here
</blockquote></details>

Done.

**Review by jethror1 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_reports_workflow/18)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @jethror1)

**Review by jethror1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_dias_reports_workflow/18#-:-N2pJ6rU3bMSTtx5Vj34:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @jethror1)

**Pull request merged**
